# do not change
name = "redirect-engine"
type = "javascript"

# config to your needs
account_id = "" # fill with account id, required
workers_dev = true # set to false if running on custom domain, default false
zone_id = "" # fill with zone/domain id, optional (for custom domains only)

# full configuration: https://developers.cloudflare.com/workers/cli-wrangler/configuration
