var cyberfolksNs = ['ns1.cyberfolks.pl.', 'ns2.cyberfolks.pl.', 'ns3.cyberfolks.pl.'];

D_EXTEND('zhp.pl',  
Delegation_A('dolnoslaska', '213.32.10.111'),
Ms365_Subdomain('dolnoslaska','zhp.pl'),
Delegation_A('kajaki.dolnoslaska.zhp.pl.', '213.32.10.111'),
Delegation_NS('boleslawiec', ['ns1.cba.pl.', 'ns2.cba.pl.', 'ns3.cba.pl.']),
Delegation_NS('bystrzycaklodzka', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
Delegation_NS('dzierzoniow', ['ns.lh.pl.', 'ns2.lighthosting.net.', 'ns2.lh.pl.']),
Delegation_A('glogow', '213.32.10.111'),
Ms365_Subdomain('glogow', 'zhp.pl'),
Delegation_NS('jawor', ['dns11.linuxpl.com.', 'ns11.linuxpl.com.']),
Delegation_NS('karkonoski', ['ns1.ehost.pl.', 'ns2.ehost.pl.']),
Delegation_NS('klodzko', ['dns8.linuxpl.com.', 'ns8.linuxpl.com.']),
Delegation_NS('legnica', cyberfolksNs),  // MS365-14080
Delegation_NS('luban', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
Delegation_NS('lubin', ['ns1.hostdmk.net.', 'ns2.hostdmk.net.']),
Delegation_A('lagiewniki', '188.165.209.195'),
Ms365_Subdomain('lagiewniki', 'zhp.pl'),
Delegation_A('milicz', '213.32.10.111'),
Ms365_Subdomain('milicz', 'zhp.pl'),
Delegation_NS('olesnica', ['ns1.datanet.pl.', 'ns2.datanet.pl.']),
Delegation_NS('olawa', ['ns12.linuxpl.com.', 'dns12.linuxpl.com.']),
Delegation_NS('srodaslaska', ['dns8.linuxpl.com.', 'ns8.linuxpl.com.']),
Delegation_NS('swidnica', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
Delegation_NS('walbrzych', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
Ms365_Subdomain('wroclaw', 'zhp.pl'),
Delegation_A_WithCfProxy('wroclaw', '178.32.149.185'),
Delegation_NS('wroclawpolnoc', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
Delegation_NS('wroclawpoludnie', ['ns.lh.pl.', 'ns2.lighthosting.net.', 'ns2.lh.pl.']),
Delegation_NS('wroclawwschod', ['ns1.hostido.net.pl.','ns2.hostido.net.pl.', 'ns3.hostido.net.pl.']),
Delegation_NS('zmigrod', ['ns.lh.pl.', 'ns2.lighthosting.net.']),
Delegation_A('trzebnica', '213.32.10.111'),
Ms365_Subdomain('trzebnica', 'zhp.pl'),
Delegation_NS('bumerang', ['ns.lh.pl.', 'ns2.lighthosting.net.', 'ns2.lh.pl.']),
Delegation_NS('rajdgranica', ['ns1.cyberfolks.pl.', 'ns2.cyberfolks.pl.', 'ns3.cyberfolks.pl.']),
Delegation_A('czarna', '213.32.10.111'),
Ms365_Subdomain('czarna', 'zhp.pl'),
Delegation_A('pobierowo', '213.32.10.111'),
Ms365_Subdomain('pobierowo', 'zhp.pl'),
Delegation_A('rozewie', '213.32.10.111'),
Ms365_Subdomain('rozewie', 'zhp.pl')
);
