D_EXTEND('zhp.pl',
    
    Delegation_NS('wielkopolska', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    
    Delegation_NS('chodziez', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('czerwonak', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('kalisz', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('kepno', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('konin', ['ns1.kylos.pl.', 'ns2.kylos.pl.']),
    Delegation_NS('kozmin', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('leszno', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('ostrowwielkopolski', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('pila', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznanjezyce', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznannowemiasto', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznanrejon', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznansrodmiescie', ['ns1.cal.pl.', 'ns2.cal.pl.']),
    Delegation_NS('poznanstaremiasto', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznanwilda', ['ns1.hostdmk.net.', 'ns2.hostdmk.net.']),
    Delegation_NS('rawicz', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('smigiel', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('trzcianka', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('turek', ['ns1.kylos.pl.', 'ns2.kylos.pl.']),
    Delegation_NS('wagrowiec', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('wolsztyn', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('wrzesnia', ['ns1.interian.pl.', 'ns3.tomkii.net.']),
    Delegation_NS('wschowa', ['ns1.atthost.pl.', 'ns2.atthost.pl.']), // MS365-9328
    Delegation_NS('zlotow', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),

    A('www.gniezno', '178.32.205.96'),
    A('gniezno', '178.32.205.96'),

    CNAME('www.poznangrunwald', 'poznangrunwald.zhp.pl.'),
    A('poznangrunwald', '94.23.27.27'),
);
