D_EXTEND('zhp.pl',
	Delegation_NS('zachpom', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('zachodniopomorska', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	
	Delegation_NS('swinoujscie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('szczecin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('szczecindabie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('szczecinek', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('szczecinpogodno', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('kolobrzeg', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('koszalin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('goleniow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('police', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('stargard', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('mysliborz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
	Delegation_NS('slawno', ['ns1.atthost.pl.', 'ns2.atthost.pl.']))
