require('./functions/ms365.js');
require('./functions/delegation.js');

var REG_NONE = NewRegistrar('none', 'NONE');
var CLOUDFLARE = NewDnsProvider('cloudflare', 'CLOUDFLAREAPI');

D('zhp.pl', REG_NONE,
    DnsProvider(CLOUDFLARE),
    DefaultTTL(3600),
    TXT('_acme-challenge.haliz', 'jd-YDJYrtRp7nynl5NEJyNrHqwrtfpm7j1H-rOJ5LfQ'),
    TXT('_github-challenge-itwzhp.gk', 'e9917cb777'),
    TXT('_github-challenge-itwzhp', 'da1510325a'),
    A('*.bytow', '95.48.248.122'),
    A('*.gdanskwrzeszczoliwa', '87.98.239.16'),
    A('*.lubelska', '193.218.152.52'),
    A('*.morenka', '87.98.239.16'),
    A('*.slupsk', '95.48.248.122'),
    CNAME('*.spis2008', 'spis2008.zhp.pl.'),
    A('*.strzelce', '185.135.90.126'),
    Delegation_NS('100latgrojec', ['ns1.nazwa.pl.', 'ns2.nazwa.pl.', 'ns3.nazwa.pl.']),
    Delegation_NS('2szczep.pabianice', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    CNAME('646napfp2tt7', 'gv-4pvab7ilnxipxn.dv.googlehosted.com.'),
    Delegation_NS('abc', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('abcabc', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('adm.pabianice', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('admin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('amonit', '109.95.158.82'),
    Delegation_NS('andrychow', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    A('archiwum', '51.75.54.175'),
    Delegation_NS('arsenal', ['ns1.unixstorm.org.', 'ns2.unixstorm.org.']),
    CNAME('autodiscover.blonie', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.celestynow', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.centrum', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.czechowice-dziedzice', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.dolnoslaska', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.gdynia', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.grodziskmazowiecki', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.grunwald', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.jpt', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.lodzka', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.lubliniec', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.lubuska', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.mazowiecka', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.milanowek', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.muzeumharcerstwa', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.opolska', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.pabianice', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.piaseczno', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.piastow', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.plock', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.pragapolnoc', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.przysucha', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.stargard', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.stoleczna', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.strzelce', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.sulejowek', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.szczecinpogodno', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.tluszcz', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.ursuswlochy', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.ursynow', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.warszawacentrum', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.warszawaursynow', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.warszawazoliborz', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.wawer', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.wola', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.wolomin', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.zabki', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.zary', 'autodiscover.outlook.com.'),
    CNAME('autodiscover', 'autodiscover.outlook.com.'),
    CNAME('autodiscover.zoliborz', 'autodiscover.outlook.com.'),
    Delegation_NS('award', ['ns1.superhost.pl.', 'ns2.superhost.pl.']),
    Delegation_NS('baldy', ['ns1.cba.pl.', 'ns2.cba.pl.', 'ns3.cba.pl.']),
    Delegation_NS('bartoszyce', ['fns1.42.pl.', 'fns2.42.pl.']),
    A('bazapajak', '91.211.221.203'),
    Delegation_NS('bazapajak', ['dns3.trustnet.pl.', 'dns.trustnet.pl.', 'dns2.trustnet.pl.']),
    A('bazy', '51.75.54.175'),
    TXT('bedzin', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('bedzin', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('berdo', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('beskidzki', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('beskidzki', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('bialapodlaska', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('bialostocka', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('bialystok', ['dns11.linuxpl.com.', 'ns11.linuxpl.com.']),
    Delegation_NS('bierutow', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    A('bip', '51.75.54.175'),
    Delegation_NS('biskupiec', ['fns1.42.pl.', 'fns2.42.pl.']),
    MX('blonie', 0, 'blonie-zhp-pl.mail.protection.outlook.com.'),
    TXT('blonie', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('blonie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('bochnia', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('boleslawiec', ['ns1.cba.pl.', 'ns2.cba.pl.', 'ns3.cba.pl.']),
    Delegation_NS('braniewo', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('brodnica', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('brzeg', ['a.eco.atman.pl.', 'b.eco.atman.pl.']),
    Delegation_NS('brzesko', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    A('brzeziny', '212.191.78.183'),
    Delegation_NS('bumerang', ['ns20.ovh.net.', 'dns20.ovh.net.']),
    Delegation_NS('bydgoszcz', ['ns1.ibc.pl.', 'ns2.ibc.pl.']),
    Delegation_NS('bystrzycaklodzka', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('bytom', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('bytom', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('carpe-noctum', ['dns.home.pl.', 'dns2.home.pl.', 'dns3.home.pl.']),
    A('cbp', '51.75.54.175'),
    Delegation_NS('celestynow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('celestynow', 0, 'celestynow-zhp-pl.mail.protection.outlook.com.'),
    TXT('celestynow', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('centrum', 0, 'centrum-zhp-pl.mail.protection.outlook.com.'),
    TXT('centrum', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('chelm', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('chelmza', ['dns10.linuxpl.com.', 'ns10.linuxpl.com.']),
    Delegation_NS('chodziez', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('chojnice', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('chojnow', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('chorzow', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('chorzow', 'v=spf1 include:spf.protection.outlook.com -all'),
    TXT('chrzanow', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('chrzanow', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('cichociemni.grojec', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('ciechanow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('cieszyn', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    A('ckr', '51.75.54.175'),
    TXT('ckr', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('cmoksong', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('cogito', ['ns1.superhost.pl.', 'ns2.superhost.pl.']),
    A('covid-zaswiadczenia', '51.75.54.175'),
    A('crowd', '213.189.38.137'),
    A('cwm', '51.75.54.175'),
    Delegation_NS('czarna', ['ns1.nazwa.pl.', 'ns2.nazwa.pl.', 'ns3.nazwa.pl.']),
    Delegation_NS('czarna2', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('czarnawoda', ['ns7.webd.pl.', 'ns5.webd.pl.']),
    Delegation_NS('czarnyszlak', ['ns1.hostinghouse.pl.', 'ns2.hostinghouse.pl.']),
    A('czat', '51.75.54.175'),
    MX('czechowice-dziedzice', 0, 'czechowicedziedzice-zhp-pl02e.mail.protection.outlook.com.'),
    Delegation_NS('czechowice-dziedzice', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('czechowice-dziedzice', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('czerwionka', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('czerwionka', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('czerwonak', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('czestochowa', ['dns.trustnet.pl.', 'dns2.trustnet.pl.']),
    A('czuwaj', '51.75.54.175'),
    Delegation_NS('czuwaj2', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('dabrowa', ['ns1.whshost.com.', 'ns2.whshost.com.']),
    TXT('dabrowagornicza', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('dabrowagornicza', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('debica', ['dns1.mydevil.net.', 'dns2.mydevil.net.']),
    A('demo-tipi', '213.189.38.138'),
    A('dev-rejestracja', '213.189.38.130'),
    A('devel', '194.29.174.10'),
    Delegation_NS('dhkielce', ['ns7.webd.pl.', 'ns5.webd.pl.']),
    A('dk', '51.75.54.175'),
    Delegation_NS('dlugoleka', ['dns10.linuxpl.com.', 'ns10.linuxpl.com.']),
    Delegation_NS('dobremiasto', ['fns1.42.pl.', 'fns2.42.pl.']),
    CNAME('dokumenty.ostroda', 'ghs.google.com.'),
    CNAME('dokumenty.stoleczna', 'ghs.google.com.'),
    CNAME('dokumenty.wolomin', 'ghs.google.com.'),
    A('dokumenty', '51.75.54.175'),
    Delegation_NS('dolinapilicy', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('dolnoslaska', ['ns1.nazwa.pl.', 'ns2.nazwa.pl.', 'ns3.nazwa.pl.']),
    TXT('dolnoslaska', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('dolnoslaska', 0, 'dolnoslaska-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('dolnoslaska2', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('dolnoslaska3', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('drezdenko', ['ns1.easyisp.pl.', 'ns2.easyisp.pl.']),
    Delegation_NS('dzialdowo', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('dzierzoniow', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('e-aos', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('e-mazowiecka', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('e', '51.75.54.175'),
    A('ed', '104.214.218.237'),
    A('edek', '104.214.218.237'),
    A('edeklaracja', '51.105.209.75'),
    A('edev', '213.189.38.133'),
    A('edev2', '213.189.38.133'),
    A('edruzyna', '213.189.38.133'),
    A('ehufiec', '213.189.38.133'),
    A('ej2020', '51.75.54.175'),
    A('ekodruzyna', '51.75.54.175'),
    Delegation_NS('elblag', ['dns1.82-300.pl.', 'dns2.82-300.pl.']),
    Delegation_NS('elk', ['fns1.42.pl.', 'fns2.42.pl.']),
    A('emblematy', '51.75.54.175'),
    CNAME('enterpriseenrollment.blonie', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.celestynow', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.centrum', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.czechowice-dziedzice', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.dolnoslaska', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.grodziskmazowiecki', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.jpt', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.lodzka', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.lubliniec', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.lubuska', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.mazowiecka', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.milanowek', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.muzeumharcerstwa', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.opolska', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.piaseczno', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.piastow', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.plock', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.pragapolnoc', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.przysucha', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.stargard', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.stoleczna', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.sulejowek', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.szczecinpogodno', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.tluszcz', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.ursynow', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.warszawacentrum', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.warszawaursynow', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.warszawazoliborz', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.wawer', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.wola', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.wolomin', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.zabki', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.zary', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseenrollment.zoliborz', 'enterpriseenrollment.manage.microsoft.com.'),
    CNAME('enterpriseregistration.blonie', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.celestynow', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.centrum', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.czechowice-dziedzice', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.dolnoslaska', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.grodziskmazowiecki', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.jpt', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.lodzka', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.lubliniec', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.lubuska', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.mazowiecka', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.milanowek', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.muzeumharcerstwa', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.opolska', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.piaseczno', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.piastow', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.plock', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.pragapolnoc', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.przysucha', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.stargard', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.stoleczna', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.sulejowek', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.szczecinpogodno', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.tluszcz', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.ursynow', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.warszawacentrum', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.warszawaursynow', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.warszawazoliborz', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.wawer', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.wola', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.wolomin', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.zabki', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.zary', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration', 'enterpriseregistration.windows.net.'),
    CNAME('enterpriseregistration.zoliborz', 'enterpriseregistration.windows.net.'),
    CNAME('ewroclaw', 'ns2.atthost.pl.'),
    Delegation_NS('exkursion', ['ns12.linuxpl.com.', 'dns12.linuxpl.com.']),
    Delegation_NS('festiwal-kielce', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('festiwalbrodnica', ['ns1.manifo.org.', 'ns2.manifo.org.']),
    Delegation_NS('folusz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('frelichowski', ['ns12.linuxpl.com.', 'dns12.linuxpl.com.', 'fns1.42.pl.']),
    A('fsj', '51.75.54.175'),
    CNAME('ftp', 'zhp.pl.'),
    Delegation_NS('garwolin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('garwolin', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('gdansk', ['dns1.thecamels.org.', 'dns2.thecamels.org.']),
    Delegation_NS('gdanska', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('gdanskaksztalcenie', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('gdanskportowa', ['dns1.thecamels.org.', 'dns2.thecamels.org.']),
    CNAME('gdanskprzymorze', 'ghs.google.com.'),
    Delegation_NS('gdanskwrzeszczoliwa', ['ns10.ovh.net.', 'dns10.ovh.net.']),
    MX('gdynia', 0, 'gdynia-zhp-pl.mail.protection.outlook.com.'),
    TXT('gdynia', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('gizycko', ['ns1.fc.pl.', 'ns2.fc.pl.']),
    Delegation_NS('gliwice', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('gliwice', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('glodowka', ['ns1.netart.pl.', 'ns2.netart.pl.']),
    Delegation_NS('glogow', ['ns1.netart.pl.', 'ns2.netart.pl.']),
    Delegation_NS('glubczyce', ['ns1.ehost.pl.', 'ns2.ehost.pl.']),
    A('gniezno', '178.32.205.96'),
    Delegation_NS('goldap', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('goleniow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('golubdobrzyn', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('google._domainkey.stoleczna', 'v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCzJSZGiRfdJXWTpOLbbTkQQHqYIVxx1SjM+3KiINhVuyHHA8xGhSK3tNadkyHCT4WvelzXrWxz02XNuL02lX/q8KuP+J8YyEHQPxIpy9c+z+aBfqIZNwchjubkozljXlOFvnzFlaz0pEGdQ9NTh/yqSP7drnafoYY4PtVTXq5cNwIDAQAB'),
    CNAME('google46a5c5b885027ebd.kielcepowiat', 'google.com.'),
    Delegation_NS('gorlice', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('gorzow', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('gostynin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('grodziskmazowiecki', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('grodziskmazowiecki', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('grodziskmazowiecki', 0, 'grodziskmazowiecki-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('grojec', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('grudziadz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('grunwald', 0, 'grunwald-zhp-pl.mail.protection.outlook.com.'),
    TXT('grunwald', 'v=spf1 include:spf.protection.outlook.com -all'),
    A('grunwald', '51.75.54.175'),
    A('haliz', '51.75.54.175'),
    A('harc2o', '51.75.54.175'),
    Delegation_NS('harcbieg', ['ns1.megiteam.pl.', 'ns2.megiteam.pl.']),
    A('hib', '51.75.54.175'),
    Delegation_NS('hme', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('hops', ['ns1.cyberfolks.pl.', 'ns2.cyberfolks.pl.', 'ns3.cyberfolks.pl.']),
    A('hp8', '213.189.38.135'),
    Delegation_NS('hrubieszow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('hsr', '51.75.54.175'),
    Delegation_NS('ilawa', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('info.lubelska', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('info.lublin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('info.lukow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('info.pulawy', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('inowlodz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('inowroclaw', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('instruktor.pabianice', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('integrationservice', '104.214.218.237'),
    A('intranet', '51.75.54.175'),
    CNAME('irc', 'chat.eu.scoutlink.net.'),
    CNAME('irc2', 'chat.scoutlink.net.'),
    Delegation_NS('jaktorow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('jamboree2015', '51.75.54.175'),
    A('jamboree2019', '51.75.54.175'),
    Delegation_NS('jaroslaw', ['dns1.home.pl.', 'dns2.home.pl.']),
    Delegation_NS('jasien.gdansk', ['ns1.gbzl.pl.', 'ns2.gbzl.pl.']),
    TXT('jastrzebiezdroj', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('jastrzebiezdroj', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('jawor', ['dns11.linuxpl.com.', 'ns11.linuxpl.com.']),
    TXT('jaworzno', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('jaworzno', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('jedrzejow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('jira', '213.189.38.137'),
    Delegation_NS('jordanow', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    TXT('jpt', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('jpt', 0, 'jpt-zhp-pl.mail.protection.outlook.com.'),
    CNAME('kalendarz.ostroda', 'ghs.google.com.'),
    CNAME('kalendarz.stoleczna', 'ghs.google.com.'),
    CNAME('kalendarz.wolomin', 'ghs.google.com.'),
    Delegation_NS('kalisz', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('karkonoski', ['ns1.ehost.pl.', 'ns2.ehost.pl.']),
    Delegation_NS('kartuzy', ['ns1.hostbox.pl.', 'ns2.hostbox.pl.']),
    Delegation_NS('katowice', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('katy', ['ns5.webd.pl.', 'ns7.webd.pl.']),
    Delegation_NS('kedzierzynkozle', ['a.eco.atman.pl.', 'b.eco.atman.pl.']),
    Delegation_NS('kepno', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('ketrzyn', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('kety', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('kielcemiasto', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('kielcepoludnie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('kielcepowiat', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('kielecka', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('klobuck', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('klobuck', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('klodzko', ['dns8.linuxpl.com.', 'ns8.linuxpl.com.']),
    Delegation_NS('kolno', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('kolobrzeg', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('komunikaty.gk', '51.75.54.175'),
    Delegation_NS('konin', ['ns1.kylos.pl.', 'ns2.kylos.pl.']),
    Delegation_NS('konskie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('konstancin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('konstantynow', '85.232.255.122'),
    Delegation_NS('kopernikanski', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('koronowo', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('korzkiew', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('kosarzyska', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('kostrzyn', ['ns7.webd.pl.', 'ns5.webd.pl.']),
    TXT('koszalin', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('koszalin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('kozmin', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('kp', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('krakowkrowodrza', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('krakownowahuta', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('krakowpodgorze', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('krakowska', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('krakowsrodmiescie', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('krapkowice', ['a.eco.atman.pl.', 'b.eco.atman.pl.']),
    Delegation_NS('krosno', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('krzeszowice', ['dns1.slaskdatacenter.pl.', 'dns2.slaskdatacenter.pl.', 'dns3.slaskdatacenter.pl.']),
    Delegation_NS('ksiegagromad', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('kucoby', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('kursharcmistrzowski', ['ns1.superhost.pl.', 'ns2.superhost.pl.']),
    A('kursy', '51.75.54.175'),
    Delegation_NS('kutno', ['dns1.mydevil.net.', 'dns2.mydevil.net.']),
    Delegation_NS('kuzniaraciborska', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('kuzniaraciborska', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('kwidzyn', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    A('lacznosc', '51.75.54.175'),
    Delegation_NS('lagiewniki', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('lancut', ['ns1.kylos.pl.', 'ns2.kylos.pl.']),
    Delegation_NS('lask', ['ns1.iq.pl.', 'ns2.iq.pl.']),
    Delegation_NS('lebork', ['dns11.linuxpl.com.', 'ns11.linuxpl.com.']),
    Delegation_NS('lednica', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('legionowo', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('lesneplemiona', '51.75.54.175'),
    Delegation_NS('leszno', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('lezajsk', ['ns1.statnet.pl.', 'ns2.statnet.pl.']),
    Delegation_NS('lidzbark', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('limev3', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('limev4', '51.75.54.175'),
    Delegation_NS('lipsko', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('lodzgorna', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('lodzka', 0, 'lodzka-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('lodzka', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('lodzka', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('lodzpolesie', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('lodzsrodmiescie', ['ns1.oiq.pl.', 'ns2.oiq.pl.']),
    Delegation_NS('lodzwidzew', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('lomza', ['ns1.datasferix.pl.', 'ns2.datasferix.pl.']),
    A('lotnictwo', '51.75.54.175'),
    A('lowicz', '85.128.206.44'),
    MX('lowicz', 10, 'lowicz.zhp.pl.'),
    Delegation_NS('luban', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('lubelska-test3', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('lubelska-test4', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('lubelska', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('lubelska', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('lubin', ['ns1.hostdmk.net.', 'ns2.hostdmk.net.']),
    TXT('lublin', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('lublin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('lubliniec', 0, 'lubliniec-zhp-pl.mail.protection.outlook.com.'),
    TXT('lubliniec', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('lubliniec', ['ns1.ehost.pl.', 'ns2.ehost.pl.']),
    TXT('lubuska', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('lubuska', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    MX('lubuska', 0, 'lubuska-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('lukow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    CNAME('lyncdiscover.blonie', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.celestynow', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.centrum', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.czechowice-dziedzice', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.dolnoslaska', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.grodziskmazowiecki', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.jpt', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.lodzka', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.lubliniec', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.lubuska', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.mazowiecka', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.milanowek', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.opolska', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.pabianice', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.piaseczno', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.piastow', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.plock', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.pragapolnoc', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.przysucha', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.stargard', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.stoleczna', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.sulejowek', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.szczecinpogodno', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.tluszcz', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.ursuswlochy', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.ursynow', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.warszawacentrum', 'webdir.online.lync.com.'),
    TXT('lyncdiscover.warszawaursynow', 'webdir.online.lync.com'),
    CNAME('lyncdiscover.warszawazoliborz', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.wawer', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.wola', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.wolomin', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.zabki', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.zary', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover', 'webdir.online.lync.com.'),
    CNAME('lyncdiscover.zoliborz', 'webdir.online.lync.com.'),
    CNAME('mail.stoleczna', 'ghs.google.com.'),
    CNAME('mail', 'zhp.pl.'),
    Delegation_NS('mailing', ['redir1.freshmail.pl.', 'redir2.freshmail.pl.']),
    Delegation_NS('mak', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('malbork', ['ns1.nazwa.pl.', 'ns2.nazwa.pl.']),
    Delegation_NS('malecz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('mam-pomysl', '213.189.38.137'),
    Delegation_NS('mazowiecka', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('mazowiecka', 0, 'mazowiecka-zhp-pl.mail.protection.outlook.com.'),
    TXT('mazowiecka', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('mazowieckazostajewdomu', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('mazowszeplock', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    CNAME('merkury.ostroda', 'merkury.homelinux.net.'),
    Delegation_NS('miastko', ['ns7.webd.pl.', 'ns5.webd.pl.']),
    Delegation_NS('miedzychod', ['ns1.hostinghouse.pl.', 'ns2.hostinghouse.pl.']),
    Delegation_NS('mielec', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    TXT('mikolow', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('mikolow', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('miks', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('milanowek', ['ns5.webd.pl.', 'ns7.webd.pl.']),
    TXT('milanowek', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('milanowek', 0, 'milanowek-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('milicz', ['ns1.keed.pl.', 'ns2.keed.pl.', 'ns3.keed.pl.']),
    Delegation_NS('minsk', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('mlawa', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('mokotow', ['ns1.unixstorm.org.', 'ns2.unixstorm.org.']),
    Delegation_NS('morag', ['fns1.42.pl.', 'fns2.42.pl.']),
    A('morenka', '87.98.239.16'),
    TXT('morenka', 'v=spf1 include:aspmx.googlemail.com ~all'),
    MX('morenka', 1, 'aspmx.l.google.com.'),
    Delegation_NS('mragowo', ['fns1.42.pl.', 'fns2.42.pl.']),
    CNAME('msoid.blonie', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.celestynow', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.centrum', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.czechowice-dziedzice', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.dolnoslaska', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.grodziskmazowiecki', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.jpt', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.lodzka', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.lubliniec', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.lubuska', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.mazowiecka', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.milanowek', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.piastow', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.plock', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.pragapolnoc', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.przysucha', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.stargard', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.stoleczna', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.sulejowek', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.szczecinpogodno', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.tluszcz', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.ursynow', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.warszawacentrum', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.warszawaursynow', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.warszawazoliborz', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.wawer', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.wola', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.wolomin', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.zabki', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.zary', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid', 'clientconfig.microsoftonline-p.net.'),
    CNAME('msoid.zoliborz', 'clientconfig.microsoftonline-p.net.'),
    Delegation_NS('mszczonow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('muzeumharcerstwa', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('muzeumharcerstwa', 0, 'muzeumharcerstwa-zhp-pl.mail.protection.outlook.com.'),
    A('muzeumharcerstwa', '185.36.169.152'),
    Delegation_NS('myslenice', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('mysliborz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('mysliborz', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('myslowice', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('myslowice', 'v=spf1 include:spf.protection.outlook.com -all'),
    CNAME('mysql', 'sql.zhp.pl.'),
    Delegation_NS('myszkow', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('myszkow', 'v=spf1 include:spf.protection.outlook.com -all'),
    A('n', '51.75.54.175'),
    Delegation_NS('namyslow', ['ns111.ovh.net.', 'dns111.ovh.net.']),
    A('natropie', '51.75.54.175'),
    Delegation_NS('nazajecia', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('nforum', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('nidzica', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('nidzica2', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('niemodlin', ['a.eco.atman.pl.', 'b.eco.atman.pl.']),
    Delegation_NS('nml', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    CNAME('nowasol', 'ghs.google.com.'),
    A('nowe', '51.75.54.175'),
    A('nowemiasto', '185.23.21.18'),
    TXT('nowydwormazowiecki', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('nowysacz', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    A('ns1.worker', '46.101.240.55'),
    A('ns2.worker', '46.101.240.55'),
    Delegation_NS('nysa', ['a.eco.atman.pl.', 'b.eco.atman.pl.']),
    Delegation_NS('oboz.krzeszowice', ['ns1.hostdns.pl.', 'ns2.hostdns.pl.']),
    Delegation_NS('ocypel', ['ns1.netmark.pl.', 'ns2.netmark.pl.']),
    A('odkrywcy', '51.75.54.175'),
    Delegation_NS('olawa', ['ns12.linuxpl.com.', 'dns12.linuxpl.com.']),
    Delegation_NS('olecko', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('olesnica', ['ns1.datanet.pl.', 'ns2.datanet.pl.']),
    Delegation_NS('olkusz', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('opal', ['ns1.webserwer.pl.', 'ns2.webserwer.pl.']),
    Delegation_NS('opoczno', ['dns12.linuxpl.com.', 'ns12.linuxpl.com.']),
    Delegation_NS('opole', ['a.eco.atman.pl.', 'b.eco.atman.pl.']),
    CNAME('opolemiasto', 'opole.zhp.pl.'),
    TXT('opolska', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('opolska', 0, 'opolska-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('opolska', ['a.eco.atman.pl.', 'b.eco.atman.pl.']),
    Delegation_NS('orneta', ['ns11.linuxpl.com.', 'dns11.linuxpl.com.']),
    Delegation_NS('ostroda', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('ostroleka', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('ostrowiec', ['dns1.onecik.pl.', 'dns2.onecik.pl.']),
    Delegation_NS('ostrowwielkopolski', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('ostrzeszow', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('oswiecim', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    TXT('otwock', 'v=spf1 include:spf.protection.outlook.com -all'),
    TXT('ovhcontrol', 'aoRqdwWKKnTDamiIqv6uqQ'),
    TXT('pabianice', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('pabianice', 0, 'pabianice-zhp-pl.mail.protection.outlook.com.'),
    A('pabianice', '79.133.210.186'),
    Delegation_NS('paluki', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('panel', '51.75.54.175'),
    A('patronus', '109.95.157.35'),
    Delegation_NS('perkoz', ['ns1.ehost.pl.', 'ns2.ehost.pl.']),
    MX('piaseczno', 0, 'piaseczno-zhp-pl.mail.protection.outlook.com.'),
    A('piaseczno', '178.32.203.125'),
    TXT('piaseczno', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('piaskidruzkow', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    MX('piastow', 0, 'piastow-zhp-pl.mail.protection.outlook.com.'),
    TXT('piastow', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('piastow', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('piekary', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('piekaryslaskie', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('pielgrzymka', ['dns.smarthost.pl.', 'dns2.smarthost.pl.', 'dns3.smarthost.pl.']),
    Delegation_NS('pila', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('piotrkow', ['ns10.az.pl.', 'ns11.az.pl.', 'ns12.az.pl.']),
    Delegation_NS('pisz', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('plock', ['dns113.ovh.net.', 'ns113.ovh.net.']),
    Delegation_NS('plonsk', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('pobierowo', ['ns1.nazwa.pl.', 'ns2.nazwa.pl.', 'ns3.nazwa.pl.']),
    Delegation_NS('pobierowo2', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    CNAME('poczta.ostroda', 'ghs.google.com.'),
    CNAME('poczta.wolomin', 'ghs.google.com.'),
    A('poczta.worker', '46.101.240.55'),
    A('poczta', '51.75.54.175'),
    Delegation_NS('podhalanski', ['dns12.linuxpl.com.', 'ns12.linuxpl.com.']),
    Delegation_NS('podkarpacka', ['dns8.linuxpl.com.', 'ns8.linuxpl.com.']),
    Delegation_NS('podkrakowski', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('police', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('polko', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('polkowice', ['ns1.netart.pl.', 'ns2.netart.pl.', 'ns3.netart.pl.']),
    A('pomoc', '213.189.38.137'),
    CNAME('portowa', 'gdanskportowa.zhp.pl.'),
    Delegation_NS('powiatwloclawek', ['ns3.biznes-host.pl.', 'ns4.biznes-host.pl.']),
    A('powodydodumy', '51.75.54.175'),
    A('poznangrunwald', '94.23.27.27'),
    Delegation_NS('poznanjezyce', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznannowemiasto', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznanrejon', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznansrodmiescie', ['ns1.cal.pl.', 'ns2.cal.pl.']),
    Delegation_NS('poznanstaremiasto', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('poznanwilda', ['ns1.hostdmk.net.', 'ns2.hostdmk.net.']),
    TXT('pragapolnoc', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('pragapolnoc', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    MX('pragapolnoc', 0, 'pragapolnoc-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('pragapoludnie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('praszka', ['a.eco.atman.pl.', 'b.eco.atman.pl.']),
    TXT('praszka', 'YCt6GUiBSQdODPJJJ9SnkA'),
    A('preprod-tipi', '213.189.38.138'),
    A('programator', '51.75.54.175'),
    Delegation_NS('przasnysz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('przerwanki', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('przeslanie', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    TXT('przysucha', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('przysucha', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('przysucha', 0, 'przysucha-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('ps', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('puck', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.']),
    Delegation_NS('pulawy', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('qnapgk', '213.189.38.134'),
    Delegation_NS('qwas', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('rada.mazowiecka', ['ns1.megiteam.pl.', 'ns2.megiteam.pl.']),
    Delegation_NS('radom', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('radommiasto', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('radomsko', ['ns1.webserwer.pl.', 'ns2.webserwer.pl.']),
    Delegation_NS('rajdgranica', ['dns1.linuxpl.com.', 'dns2.linuxpl.com.', 'dns3.linuxpl.com.']),
    A('rajdodkrywcow', '51.75.54.175'),
    Delegation_NS('rajdscenariusz', ['ns1.8p.pl.', 'ns2.8p.pl.']),
    Delegation_NS('rajdswietokrzyski', ['ns5.webd.pl.', 'ns7.webd.pl.']),
    A('raporty.odkrywcy', '51.75.54.175'),
    Delegation_NS('rawicz', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    A('repozytorium', '51.75.54.175'),
    TXT('rn', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('rnz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('rodlo', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('rozewie', ['ns1.nazwa.pl.', 'ns2.nazwa.pl.', 'ns3.nazwa.pl.']),
    Delegation_NS('rudaslaska', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('rybnik', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('rybnik', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('rydultowy', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('rydultowy', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('ryki', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('ryki', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('rzeszow', ['ns1.kylos.pl.', 'ns2.kylos.pl.']),
    A('sapi', '213.189.38.133'),
    CNAME('selector1._domainkey', 'selector1-zhp-pl._domainkey.gkzhp.onmicrosoft.com.'),
    CNAME('selector2._domainkey', 'selector2-zhp-pl._domainkey.gkzhp.onmicrosoft.com.'),
    A('sezam', '89.171.90.254'),
    Delegation_NS('siedlce', ['ns1.manifo.pl.', 'ns2.manifo.pl.']),
    Delegation_NS('siemianowice', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('siemianowice', 'v=spf1 include:spf.protection.outlook.com -all'),
    A('sieradz', '85.232.255.122'),
    Delegation_NS('sierpc', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('siodemka', ['ns1.cal.pl.', 'ns2.cal.pl.']),
    CNAME('sip.blonie', 'sipdir.online.lync.com.'),
    CNAME('sip.celestynow', 'sipdir.online.lync.com.'),
    CNAME('sip.centrum', 'sipdir.online.lync.com.'),
    CNAME('sip.czechowice-dziedzice', 'sipdir.online.lync.com.'),
    CNAME('sip.dolnoslaska', 'sipdir.online.lync.com.'),
    CNAME('sip.grodziskmazowiecki', 'sipdir.online.lync.com.'),
    CNAME('sip.jpt', 'sipdir.online.lync.com.'),
    CNAME('sip.lodzka', 'sipdir.online.lync.com.'),
    CNAME('sip.lubliniec', 'sipdir.online.lync.com.'),
    CNAME('sip.lubuska', 'sipdir.online.lync.com.'),
    CNAME('sip.mazowiecka', 'sipdir.online.lync.com.'),
    CNAME('sip.milanowek', 'sipdir.online.lync.com.'),
    CNAME('sip.opolska', 'sipdir.online.lync.com.'),
    CNAME('sip.pabianice', 'sipdir.online.lync.com.'),
    CNAME('sip.piaseczno', 'sipdir.online.lync.com.'),
    CNAME('sip.piastow', 'sipdir.online.lync.com.'),
    CNAME('sip.plock', 'sipdir.online.lync.com.'),
    CNAME('sip.pragapolnoc', 'sipdir.online.lync.com.'),
    CNAME('sip.przysucha', 'sipdir.online.lync.com.'),
    CNAME('sip.stargard', 'sipdir.online.lync.com.'),
    CNAME('sip.stoleczna', 'sipdir.online.lync.com.'),
    CNAME('sip.sulejowek', 'sipdir.online.lync.com.'),
    CNAME('sip.szczecinpogodno', 'sipdir.online.lync.com.'),
    CNAME('sip.tluszcz', 'sipdir.online.lync.com.'),
    CNAME('sip.ursuswlochy', 'sipdir.online.lync.com.'),
    CNAME('sip.ursynow', 'sipdir.online.lync.com.'),
    CNAME('sip.warszawacentrum', 'sipdir.online.lync.com.'),
    CNAME('sip.warszawaursynow', 'sipdir.online.lync.com.'),
    CNAME('sip.warszawazoliborz', 'sipdir.online.lync.com.'),
    CNAME('sip.wawer', 'sipdir.online.lync.com.'),
    CNAME('sip.wola', 'sipdir.online.lync.com.'),
    CNAME('sip.wolomin', 'sipdir.online.lync.com.'),
    CNAME('sip.zabki', 'sipdir.online.lync.com.'),
    CNAME('sip.zary', 'sipdir.online.lync.com.'),
    CNAME('sip', 'sipdir.online.lync.com.'),
    CNAME('sip.zoliborz', 'sipdir.online.lync.com.'),
    CNAME('sites.stoleczna', 'ghs.google.com.'),
    Delegation_NS('skarzysko', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('skierniewice', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('sl', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('sl1', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('sl2', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('slaska', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('slaska', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('slawno', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('slubice', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('slupca', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('slupsk', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    A('sluzba', '51.75.54.175'),
    Delegation_NS('smigiel', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('sochaczew', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('sokolow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('sopot', ['ns1.ehost.pl.', 'ns2.ehost.pl.']),
    TXT('sosnowiec', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('sosnowiec', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    A('spadochroniarze', '51.75.54.175'),
    A('specjalnosci', '51.75.54.175'),
    A('spis2008', '213.189.38.133'),
    Delegation_NS('sroda', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('srodaslaska', ['dns8.linuxpl.com.', 'ns8.linuxpl.com.']),
    Delegation_NS('stalowawola', ['ns1.domena.pl.', 'ns2.domena.pl.']),
    Delegation_NS('stanica.mazowiecka', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('starachowice', ['ns5.webd.pl.', 'ns7.webd.pl.']),
    Delegation_NS('starekarpno', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    MX('stargard', 0, 'stargard-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('stargard', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('stargard', 'v=spf1 include:spf.protection.outlook.com -a'),
    Delegation_NS('starogard', ['ns1.contabo.net.', 'ns2.contabo.net.', 'ns3.contabo.net.']),
    Delegation_NS('starosiele', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('starszyzna', '51.75.54.175'),
    A('starszyzna2', '51.75.54.175'),
    CNAME('start.ostroda', 'ghs.google.com.'),
    CNAME('start.stoleczna', 'ghs.google.com.'),
    Delegation_NS('staszow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('stock', '51.75.54.175'),
    Delegation_NS('stoleczna', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('stoleczna', 'v=spf1 include:spf.protection.outlook.com -all'),
    A('stopka', '51.75.54.175'),
    Delegation_NS('strategia2025', ['ns7.wixdns.net.', 'ns6.wixdns.net.']),
    Delegation_NS('stronanidzica', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    CNAME('strony.wolomin', 'ghs.google.com.'),
    A('strony', '51.75.54.175'),
    MX('strzelce', 0, 'strzelce-zhp-pl.mail.protection.outlook.com.'),
    A('strzelce', '185.135.90.126'),
    TXT('strzelce', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('sulejowek', 0, 'sulejowek-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('sulejowek', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('sulejowek', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('superstrona', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('swiatlo', '51.75.54.175'),
    Delegation_NS('swidnica', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('swidnik', ['ns1.netart.pl.', 'ns2.netart.pl.', 'ns3.netart.pl.']),
    Delegation_NS('swiecie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('swinoujscie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('swinoujscie', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('szaradruzyna', ['d.ns1.pl.', 'd.ns2.pl.']),
    Delegation_NS('szczecin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('szczecin', 'v=spf1 include:spf.protection.outlook.com -all'),
    TXT('szczecindabie', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('szczecindabie', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('szczecinek', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('szczecinek', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('szczecinpogodno', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('szprotawa', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('sztum', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('tarnow', ['ns1.kei.pl.', 'ns2.kei.pl.']),
    TXT('tarnowskiegory', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('tarnowskiegory', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('tczew', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    A('test-rejestracja', '213.189.38.130'),
    Delegation_NS('test1234', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('tezm-mazowiecka', ['ns1.x14.eu.', 'ns3.x25.pl.']),
    A('tipi', '51.83.143.218'),
    MX('tluszcz', 0, 'tluszcz-zhp-pl.mail.protection.outlook.com.'),
    TXT('tluszcz', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('tomaszowlubelski', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('tomaszowmaz', ['ns1.he.net.', 'ns2.he.net.', 'ns3.he.net.']),
    Delegation_NS('torun', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('trzcianka', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('trzebinia', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('turek', ['ns1.kylos.pl.', 'ns2.kylos.pl.']),
    A('turniej', '51.75.54.175'),
    A('turniejgromad', '51.75.54.175'),
    Delegation_NS('tychy', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('tychy', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('uniejow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('ursuswlochy', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('ursynow', 0, 'ursynow-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('ursynow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('ursynow', 'v=spf1 include:spf.protection.outlook.com -all'),
    A('veturi', '213.189.38.133'),
    CNAME('vpn.ostroda', 'merkury.ostroda.zhp.pl.'),
    A('vpngk', '213.189.38.130'),
    Delegation_NS('wadowice', ['ns11.linuxpl.com.', 'dns11.linuxpl.com.']),
    Delegation_NS('wagrowiec', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('walbrzych', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('warminski', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('warminskomazurska', ['fns1.42.pl.', 'fns2.42.pl.']),
    MX('warszawacentrum', 0, 'warszawacentrum-zhp-pl.mail.protection.outlook.com.'),
    TXT('warszawacentrum', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('warszawacentrum', ['dns10.linuxpl.com.', 'ns10.linuxpl.com.']),
    Delegation_NS('warszawaochota', ['ns100.ovh.net.', 'dns100.ovh.net.']),
    CNAME('warszawapragapd', 'pragapoludnie.zhp.pl.'),
    MX('warszawaursynow', 0, 'warszawaursynow-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('warszawaursynow', ['ns2.linuxpl.com.', 'dns2.linuxpl.com.']),
    TXT('warszawaursynow', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('warszawazoliborz', 0, 'warszawazoliborz-zhp-pl.mail.protection.outlook.com.'),
    TXT('warszawazoliborz', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('warszawazoliborz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('wataha.piaseczno', ['dns.home.pl.', 'dns2.home.pl.', 'dns3.home.pl.']),
    A('watra', '51.75.54.175'),
    Delegation_NS('wawer', ['ns1.x14.eu.', 'ns3.x25.pl.']),
    TXT('wegierskagorka', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('wegierskagorka', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('wegorzewo', ['fns1.42.pl.', 'fns2.42.pl.']),
    Delegation_NS('wegrow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('wejherowo', ['ns1.iq.pl.', 'ns2.iq.pl.']),
    Delegation_NS('westerplatte', ['ns1.hekko.net.pl.', 'ns2.hekko.net.pl.']),
    Delegation_NS('wieliczka', ['ns1.nazwa.pl.', 'ns2.nazwa.pl.', 'ns3.nazwa.pl.']),
    Delegation_NS('wielkopolska', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    A('wilczysko', '109.95.157.35'),
    Delegation_NS('winiec', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('wloclawek', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    CNAME('wloclawekpowiat', 'powiatwloclawek.zhp.pl.'),
    Delegation_NS('wm', ['fns1.42.pl.', 'fns2.42.pl.']),
    A('wntgk', '213.189.38.130'),
    TXT('wodzislaw', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('wodzislaw', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('wola', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('wola', 0, 'wola-zhp-pl.mail.protection.outlook.com.'),
    TXT('wola', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('wolomin', 0, 'wolomin-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('wolomin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('wolomin', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('wolow', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.']),
    Delegation_NS('wolsztyn', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('work', '51.75.54.175'),
    Delegation_NS('wroclaw', ['dns20.ovh.net.', 'ns20.ovh.net.']),
    Delegation_NS('wroclawpolnoc', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('wroclawpoludnie', ['ns1.nazwa.pl.', 'ns2.nazwa.pl.', 'ns3.nazwa.pl.']),
    Delegation_NS('wroclawwschod', ['ns.lh.pl.', 'ns2.lighthosting.net.']),
    A('wrzawa.stoleczna', '46.229.151.194'),
    Delegation_NS('wrzesnia', ['ns1.interian.pl.', 'ns3.tomkii.net.']),
    A('wschowa', '87.98.239.3'),
    Delegation_NS('wschowa', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    AAAA('wschowa', '2001:41d0:1:1b00:87:98:239:3'),
    CNAME('www.czarnyszlak', 'czarnyszlak.zhp.pl.'),
    CNAME('www.gdanskprzymorze', 'ghs.google.com.'),
    A('www.gniezno', '178.32.205.96'),
    CNAME('www.haliz', 'haliz.zhp.pl.'),
    CNAME('www.lancut', 'lancut.zhp.pl.'),
    CNAME('www.lowicz', 'lowicz.zhp.pl.'),
    CNAME('www.nowasol', 'ghs.google.com.'),
    CNAME('www.piaseczno', 'piaseczno.zhp.pl.'),
    CNAME('www.poznangrunwald', 'poznangrunwald.zhp.pl.'),
    CNAME('www.rajdswietokrzyski', 'rajdswietokrzyski.zhp.pl.'),
    CNAME('www.slupsk', 'slupsk.zhp.pl.'),
    A('www.starszyzna', '51.75.54.175'),
    A('www.strzelce', '185.135.90.126'),
    CNAME('www.wrzawa.stoleczna', 'wrzawa.stoleczna.zhp.pl.'),
    AAAA('www.wschowa', '2001:41d0:1:1b00:87:98:239:3'),
    A('www.wschowa', '87.98.239.3'),
    A('www.zamosc', '83.19.99.158'),
    CNAME('www', 'zhp.pl.'),
    CNAME('www.zk.wntgk', 'zk.wntgk.zhp.pl.'),
    Delegation_NS('wyszkow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('wzlot', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    CNAME('youthwave', 'zhp.pl.'),
    Delegation_NS('zabki', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    MX('zabki', 0, 'zabki-zhp-pl.mail.protection.outlook.com.'),
    TXT('zabki', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('zabkowiceslaskie', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.']),
    TXT('zabrze', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('zabrze', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('zachpom', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('zalecze', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('zamosc', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    A('zapytaj', '51.75.54.175'),
    MX('zary', 0, 'zary-zhp-pl.mail.protection.outlook.com.'),
    TXT('zary', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('zawiercie', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('zawiercie', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('zdunskawola', ['fns1.42.pl.', 'fns2.42.pl.']),
    A('zeus', '213.189.38.137'),
    Delegation_NS('zgierz', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    A('zgloszenia-rajdodkrywcow', '51.75.54.175'),
    MX('@', 10, 'zhp-pl.mail.protection.outlook.com.'),
    TXT('@', 'v=spf1 include:spf.protection.outlook.com -all'),
    A('@', '51.75.54.175'),
    A('zhpbaluty', '217.76.113.42'),
    Delegation_NS('zielonagora', ['ns1.zenbox.pl.', 'ns2.zenbox.pl.']),
    Delegation_NS('zielonanuta', ['ns1.he.net.', 'ns2.he.net.', 'ns3.he.net.']),
    TXT('zielonka', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('zielonka', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('ziemiarzeszowska', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.', 'ns3.ogicom.pl.']),
    Delegation_NS('zkk.lodzpolesie', ['ns-pl.1and1-dns.pl.', 'ns-pl.1and1-dns.biz.']),
    Delegation_NS('zlotow', ['ns1.interian.pl.', 'ns3.tomkii.net.', 'jasmin.bracz.edu.pl.']),
    Delegation_NS('zmigrod', ['ns.lh.pl.', 'ns2.lighthosting.net.']),
    TXT('zoliborz', 'v=spf1 include:spf.protection.outlook.com -all'),
    MX('zoliborz', 0, 'zoliborz-zhp-pl.mail.protection.outlook.com.'),
    Delegation_NS('zoliborz', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    TXT('zory', 'v=spf1 include:spf.protection.outlook.com -all'),
    Delegation_NS('zory', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    Delegation_NS('zuchy.pabianice', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('zuromin', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('zychlin', ['ns1.ogicom.pl.', 'ns2.ogicom.pl.']),
    Delegation_NS('zyrardow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
    Delegation_NS('zywiec', ['ns1.dhosting.pl.', 'ns2.dhosting.pl.']),
    TXT('zywiec', 'v=spf1 include:spf.protection.outlook.com -all')
);
