name: Preview DNS changes

on:
  workflow_run:
    workflows: ["Build DNS config"]
    types: [ completed ]

# based on https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

jobs:
  dnscontrol:
    name: DNSControl
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    container:
      image: stackexchange/dnscontrol
    steps:
      - uses: actions/checkout@v2

      - name: Download build DNS config
        uses: actions/github-script@v3
        with:
          script: |
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id }},
            });
            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "dns-config"
            })[0];
            var download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/dns-config.json.zip', Buffer.from(download.data));

      - name: Preview DNS changes
        id: dnscontrol_preview
        run: |
            unzip dns-config.json.zip -q
            dnscontrol preview --config domains/dnsconfig.js --ir dns-config.json | head -n 250
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          AZURE_DNS_MANAGEMENT_CREDENTIALS: ${{ secrets.AZURE_DNS_MANAGEMENT_CREDENTIALS }}

      - name: Add comment to the pull request
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              \`\`\`
              ${{ steps.dnscontrol_preview.outputs.output }}
              \`\`\`
              `
            })
