# name: Preview DNS zone

# on: pull_request

# jobs:
#   dnscontrol:
#     name: DNSControl
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - name: Preview DNS zone
#         uses: koenrh/dnscontrol-action@51da3a98b54bb4c86af661fa79b5984eba60c3b9 #v3
#         id: dnscontrol_preview
#         env:
#           CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           AZURE_DNS_MANAGEMENT_CREDENTIALS: ${{ secrets.AZURE_DNS_MANAGEMENT_CREDENTIALS }}
#         with:
#           args: preview

#       - name: Add comment to the pull request
#         uses: actions/github-script@v3
#         with:
#           github-token: ${{secrets.GITHUB_TOKEN}}
#           script: |
#             github.issues.createComment({
#               issue_number: context.issue.number,
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               body: `
#               # DNSControl preview output
#               \`\`\`
#               ${{ steps.dnscontrol_preview.outputs.output }}
#               \`\`\`
#               `
#             })
