name: Preview DNS zone

on: pull_request

jobs:
  dnscontrol:
    name: DNSControl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Preview DNS zone
        uses: koenrh/dnscontrol-action@v3
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          args: preview