name: Build DNS config

on: pull_request

jobs:
  dnscontrol:
    name: DNSControl
    runs-on: ubuntu-latest
    container:
      image: stackexchange/dnscontrol:v3.14.0
    steps:
      - uses: actions/checkout@v4

      - name: Generate DNS config
        run: |
            mkdir dns-config
            dnscontrol print-ir --config domains/dnsconfig.js --out dns-config/dns-config.json
            echo ${{ github.event.number }} > dns-config/pr-number

      - name: Publish DNS zone as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dns-config
          path: dns-config

  test:
    name: Test DNS settings
    needs: dnscontrol
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get DNS zone artifact
        uses: actions/download-artifact@v4
        with:
          name: dns-config

      - name: Run tests
        shell: pwsh
        run: Invoke-Pester .github/tests.ps1 -Passthru
