name: "Pull Request Labeler"
on: pull_request

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@main
      name: Label the pull request
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
