name: Test redirects

on:
    pull_request: # TODO split it to make it work on forks
        paths:
            - "domains/redirects/**"

env:
    AZURE_SUBSCRIPTION_ID: 35e22786-93ea-47c8-902a-16e9d0f03e17
    AZURE_RESOURCE_GROUP: zhp-redirects-engine

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            # App (Node) tests
            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: "14"
            -   name: Install dependiences
                run: npm install
                working-directory: ./domains/redirects
            -   name: Run tests
                run: npm run test
                working-directory: ./domains/redirects

            # Azure ARM file tests
            -   name: Login to Azure
                uses: azure/login@v1
                with:
                    creds: ${{ secrets.AZURE_REDIRECTS_DEPLOY_CREDENTIALS }}
            -   name: Extract list of domains
                shell: pwsh
                run: |
                    $domains = Get-Item domains/redirects/redirectFiles/*.json |
                        Where-Object { -not $_.Name.EndsWith('.schema.json') } |
                        Where-Object { $_.Name -ne 'example.com.json') } |
                        Foreach-Object {
                            $base = $_.Name -replace '.json'
                            $subdomains = Get-Content $_ |
                                ConvertFrom-Json |
                                Get-Member -Type NoteProperty |
                                Where-Object {-not $_.Name.StartsWith('$') } |
                                Foreach-Object { $domains += $_.Name + '.' + $base }
                        }
                    echo "Domains: " + ($domains | ConvertTo-Json -Compress)
                    echo 'DOMAINS=' + ($domains | ConvertTo-Json -Compress) | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

            -   name: Test ARM
                uses: azure/arm-deploy@v1
                with:
                    deploymentMode: Validate
                    subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
                    resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
                    template: ./domains/redirects/redirects.arm.json
                    parameters: domains=${{ env.DOMAINS }}

