name: Test redirects

on:
    pull_request_target:
        paths:
            - "domains/redirects/**"

env:
    AZURE_SUBSCRIPTION_ID: #insert subscription ID
    AZURE_RESOURCE_GROUP: #insert resource group name

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            # App (Node) tests
            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: "14"
            -   name: Install dependiences
                run: npm install
                working-directory: ./domains/redirects
            -   name: Run tests
                run: npm run test
                working-directory: ./domains/redirects
            # Azure ARM file tests
            -   name: Login to Azure
                uses: azure/login@v1
                with:
                    creds: ${{ secrets.AZURE_CREDENTIALS }}
            -   name: Test ARM
                uses: azure/arm-deploy@v1
                with:
                    deploymentMode: Validate
                    subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
                    resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
                    template: ./domains/redirects/redirects.arm.json

