name: Test redirects

on:
    pull_request: # TODO split it to make it work on forks
        paths:
            - "domains/redirects/**"

env:
    AZURE_SUBSCRIPTION_ID: 35e22786-93ea-47c8-902a-16e9d0f03e17
    AZURE_RESOURCE_GROUP: zhp-redirects-engine

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            # App (Node) tests
            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: "18"
            -   name: Install dependiences
                run: npm ci
                working-directory: ./domains/redirects
            -   name: Run tests
                run: npm run test
                working-directory: ./domains/redirects

            # Azure ARM file tests
            -   name: Login to Azure
                uses: azure/login@v2
                with:
                    creds: ${{ secrets.AZURE_REDIRECTS_DEPLOY_CREDENTIALS }}
            -   name: Extract list of domains
                shell: pwsh
                run: .github/Create-ParamFile.ps1
            -   name: Test ARM
                uses: azure/arm-deploy@v2
                with:
                    deploymentMode: Validate
                    subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
                    resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
                    template: ./domains/redirects/redirects.arm.json
                    parameters: ./domain.parameters.json

