name: Push redirect engine

on:
    push:
        branches:
            - "main"
        paths:
            - "domains/redirects/**"

env:
    AZURE_FUNCTIONAPP_NAME: #insert function app name
    AZURE_FUNCTIONAPP_PACKAGE_PATH: ./domains/redirects # application path in repo

jobs:
    deploy:
        name: Deploy to Azure Functions
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: Deploy
                uses: Azure/functions-action@v1
                with:
                    app-name: ${{env.AZURE_FUNCTIONAPP_NAME}}
                    package: ${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}
                    publish-profile: ${{secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE}}
