name: Test redirects

on:
    pull_request: # TODO split it to make it work on forks
        paths:
            - "domains/redirects/**"

env:
    AZURE_SUBSCRIPTION_ID: 69111246-db23-463c-82b2-7815ed5f8a1a
    AZURE_RESOURCE_GROUP: zhp-redirects-engine

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            # App (Node) tests
            -   name: Setup Node
                uses: actions/setup-node@v2
                with:
                    node-version: "14"
            -   name: Install dependiences
                run: npm install
                working-directory: ./domains/redirects
            -   name: Run tests
                run: npm run test
                working-directory: ./domains/redirects

            # Azure ARM file tests
            -   name: Login to Azure
                uses: azure/login@v1
                with:
                    creds: ${{ secrets.AZURE_REDIRECTS_DEPLOY_CREDENTIALS }}
            -   name: Extract list of domains
                shell: pwsh
                run: |
                    $domains = Get-Item domains/redirects/redirectFiles/*.json |
                        Where-Object { -not $_.Name.EndsWith('.schema.json') } |
                        Where-Object { $_.Name -ne 'example.com.json' } |
                        Foreach-Object {
                            $base = $_.Name -replace '.json'
                            Get-Content $_ |
                                ConvertFrom-Json |
                                Get-Member -Type NoteProperty |
                                Where-Object {-not $_.Name.StartsWith('$') } |
                                Foreach-Object { $_.Name + '.' + $base }
                        }
                    $domainsJson = $domains | ConvertTo-Json -Compress
                    Write-Output "Domains: $domainsJson"
                    Write-Output "
                    {
                        `"`$schema`": `"https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#`",
                        `"contentVersion`": `"1.0.0.0`",
                        `"parameters`": {
                            `"domains`": {
                                `"value`": $domainsJson
                            }
                        }
                    }" > domain.parameters.json

            -   name: Test ARM
                uses: azure/arm-deploy@v1
                with:
                    deploymentMode: Validate
                    subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
                    resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
                    template: ./domains/redirects/redirects.arm.json
                    parameters: ./domain.parameters.json

